# Tag 1. Kapitel 2. Matrix

## Lektion 12. Matrix Arithmetik

Wir können mit Matrizen mathematische Operationen Element für Element durchführen, genau wie mit Vektoren. Dabei sollten ggf. beide Matrizen gleiche Anzahl an Zeilen und Spalten haben. Schauen wir uns einige Beispiele an:

In [1]:
mat <- matrix(1:16,byrow=TRUE,nrow=4)

In [4]:
print('1. Definierte Matrix mat1')
mat

[1] "1. Definierte Matrix mat1"


[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

In [3]:
# Multiplikation
mat
mat * 2

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[,1] [,2] [,3] [,4]
[1,]  2    4    6    8  
[2,] 10   12   14   16  
[3,] 18   20   22   24  
[4,] 26   28   30   32

In [5]:
# Division (1)
mat
1 / mat

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[,1]       [,2]       [,3]       [,4]      
[1,] 1.00000000 0.50000000 0.33333333 0.25000000
[2,] 0.20000000 0.16666667 0.14285714 0.12500000
[3,] 0.11111111 0.10000000 0.09090909 0.08333333
[4,] 0.07692308 0.07142857 0.06666667 0.06250000

In [6]:
# Division (2)
mat
mat / 10

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[,1] [,2] [,3] [,4]
[1,] 0.1  0.2  0.3  0.4 
[2,] 0.5  0.6  0.7  0.8 
[3,] 0.9  1.0  1.1  1.2 
[4,] 1.3  1.4  1.5  1.6

In [7]:
# Potenz (1)
mat
mat ^ 2

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[,1] [,2] [,3] [,4]
[1,]   1    4    9   16 
[2,]  25   36   49   64 
[3,]  81  100  121  144 
[4,] 169  196  225  256

## Vergleichsoperatoren mit Matrizen

Wir können des Weiteren Vergleichsoperatoren auf eine ganze Matrix anwenden, was uns eine Matrix logischer Werte als Ergebnis gibt.

In [8]:
mat
mat > 8

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[,1]  [,2]  [,3]  [,4] 
[1,] FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE
[3,]  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE

## Matrix Arithmetik mit mehrere Matrizen

Wir können außerdem Arithmetik auf mehrere Matrizen anwenden. Ein Beispiel:

In [9]:
print('1. Definierte Matrix mat1')
mat

[1] "1. Definierte Matrix mat1"


[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

In [11]:
mat2 <- matrix(c(16,10,22,11,55,10,22,1,3,4,5,12,3,44,-11,77),byrow=TRUE,nrow=4)

print('2. Definierte Matrix mat2')
mat2

[1] "2. Definierte Matrix mat2"


[,1] [,2] [,3] [,4]
[1,] 16   10    22  11  
[2,] 55   10    22   1  
[3,]  3    4     5  12  
[4,]  3   44   -11  77

In [12]:
# Addition
print('mat1 + mat2')
mat + mat2

[1] "mat1 + mat2"


[,1] [,2] [,3] [,4]
[1,] 17   12   25   15  
[2,] 60   16   29    9  
[3,] 12   14   16   24  
[4,] 16   58    4   93

In [150]:
# Division
print('Matrix mat1')
mat
print('Matrix mat2')
mat2

print('mat2 /  mat1')
mat2 / mat

[1] "Matrix mat1"


[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[1] "Matrix mat2"


[,1] [,2] [,3] [,4]
[1,] 16   10    22  11  
[2,] 55   10    22   1  
[3,]  3    4     5  12  
[4,]  3   44   -11  77

[1] "mat2 /  mat1"


[,1]       [,2]     [,3]       [,4]  
[1,] 16.0000000 5.000000  7.3333333 2.7500
[2,] 11.0000000 1.666667  3.1428571 0.1250
[3,]  0.3333333 0.400000  0.4545455 1.0000
[4,]  0.2307692 3.142857 -0.7333333 4.8125

In [13]:
# Potenz
print('Matrix mat2')
mat2
print('Matrix mat1')
mat

print('mat2 ^ (hoch) mat1')
mat2 ^ mat

[1] "Matrix mat2"


[,1] [,2] [,3] [,4]
[1,] 16   10    22  11  
[2,] 55   10    22   1  
[3,]  3    4     5  12  
[4,]  3   44   -11  77

[1] "Matrix mat1"


[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[1] "mat2 ^ (hoch) mat1"


[,1]      [,2]         [,3]          [,4]        
[1,]        16 1.000000e+02  1.064800e+04 1.464100e+04
[2,] 503284375 1.000000e+06  2.494358e+09 1.000000e+00
[3,]     19683 1.048576e+06  4.882813e+07 8.916100e+12
[4,]   1594323 1.019383e+23 -4.177248e+15 1.527044e+30

In [14]:
# Multiplikation (elementweise)
print('Matrix mat1')
mat

print('Matrix mat2')
mat2


print('mat1 * mat2 (elementweise)')
mat * mat2

[1] "Matrix mat1"


[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

[1] "Matrix mat2"


[,1] [,2] [,3] [,4]
[1,] 16   10    22  11  
[2,] 55   10    22   1  
[3,]  3    4     5  12  
[4,]  3   44   -11  77

[1] "mat1 * mat2 (elementweise)"


[,1] [,2] [,3] [,4]
[1,]  16   20    66   44
[2,] 275   60   154    8
[3,]  27   40    55  144
[4,]  39  616  -165 1232

##### Achtung! Bitte nich mit einer "echten" Matrix-Multiplikation (Matrix-Produkt) verwechseln! 

## Matrix Multiplikation (Matrix-Produkt)

Eine kurze Notiz zur Multiplikation von Matrizen in R. Die Multiplikation Element für Element können wir mit dem * Zeichen durchführen. Eine "echte" [Matrizenmultiplikation](https://de.wikipedia.org/wiki/Matrizenmultiplikation) liefert ein Matrix-Produkt als Egebnis zurück. Ein Matrix-Produkt wird mit R wie folgt berechnet:

### Matrix-Produkt:

Gegeben seien die beiden reellen Matrizen:

 und 

Da die Matrix **A** ebenso viele Spalten wie die Matrix **B** Zeilen besitzt, ist die Matrizenmultiplikation **A** x **B** durchführbar. Nachdem **A** zwei Zeilen und **B** zwei Spalten hat, wird das Matrizenprodukt ebenfalls zwei Zeilen und Spalten aufweisen. Zur Berechnung des ersten Matrixelements der Ergebnismatrix werden die Produkte der entsprechenden Einträge der ersten Zeile von **A** und der ersten Spalte von **B** aufsummiert (die Sternchen stehen für noch nicht berechnete Elemente):



Für das nächste Element der Ergebnismatrix in der ersten Zeile und zweiten Spalte wird entsprechend die erste Zeile von **A** und die zweite Spalte von **B** verwendet:



Dieses Rechenschema setzt sich nun in der zweiten Zeile und ersten Spalte fort:



Es wiederholt sich bei dem letzten Element in der zweiten Zeile und zweiten Spalte:



#### Das Ergebnis ist das Matrizenprodukt A x B

###### Achtung! Spalten-Anzahl von Matrix A soll der Zeilen-Anzahl von Matrix B gleich sein

D.h. wenn man eine Matrix **A(m,n)** mit einer anaderen Matrix **B(l,k)** multpliziert (**m,n** und **l,k** ist die Zeile-/Spalten-Anzahl von jeweilige Matrizen), bekommt man eine neue Matrix **C(m,k)** als Matrix-Produkt. 


Weieter Infos s. hier: [Matrizenmultiplikation](https://de.wikipedia.org/wiki/Matrizenmultiplikation) 

Nachfolgende Ausdrücke setzen Multplikation gleichen Matrizen als R Code um.

In [15]:
# 1. Matrix 2 x 3 erstellen 
A <- matrix(c(3,2,1 ,1,0,2),byrow=TRUE,nrow=2)
A

[,1] [,2] [,3]
[1,] 3    2    1   
[2,] 1    0    2

In [16]:
# 2. Matrix 3 x 2 erstellen 
B <- matrix(c(1,0,4 ,2,1,0),byrow=FALSE,nrow=3)
B

[,1] [,2]
[1,] 1    2   
[2,] 0    1   
[3,] 4    0

In [17]:
# "Echte" Matrizenmultiplikation - Matrix-Produkt - berechnen
C <- A %*% B
C

[,1] [,2]
[1,] 7    8   
[2,] 9    2

In [18]:
# Noch ein Beispiel:
A # Matrix 2 x 3
D <- matrix(c(1,0,4 ,2,1,0 ,9,9,-11 ,7,-99,17),byrow=FALSE,nrow=3) 
D # Matrix 3 x 4

[,1] [,2] [,3]
[1,] 3    2    1   
[2,] 1    0    2

[,1] [,2] [,3] [,4]
[1,] 1    2      9    7 
[2,] 0    1      9  -99 
[3,] 4    0    -11   17

In [19]:
# Matrix-Produkt 
E <- A %*% D 
E # Matrix 2 x 4

[,1] [,2] [,3] [,4]
[1,] 7    8     34  -160
[2,] 9    2    -13    41

Herzlichen Glückwunsch! Sie sind mit Lektion 12 fertig!