# Tag 1. Kapitel 2. Matrix

## Lektion 11. Matrix erstellen

Wir haben bereits Vektoren behandelt, die es uns erlauben indexierte Elemente zu speichern. Eine Matrix erlaubt es uns darüberhinaus zweidimensionale Datenststruckturen von Elementen des selben Datentyps zu erstellen.

Bevor wir jetzt mit den Matrizen beginnen sollten wir uns noch einen kleinen Tipp zur Erstellung von sequenziellen Zahlenfolgen anschauen. Wir können die *Doppelpunkt-Notation* verwenden, die wir vom Slicing kennen, um sequentielle Vektoren zu erstellen:

In [1]:
1:6

[1] 1 2 3 4 5 6

In [2]:
v <- 1:6
v

[1] 1 2 3 4 5 6

Um jetzt eine Matrix in R zu erstellen nutzen wir die `matrix()` Funktion. Wir können einen Vektor übergeben:

In [3]:
matrix(v)

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6

Wir haben eine zweidimensionale Matrix mit 6 Zeilen und einer Spalte erhalten. Um die Anzahl der Zeilen festzulegen, übergibt man das `nrow` Argument:

In [6]:
matrix(v,nrow=2)
matrix(v,byrow=FALSE,nrow=2)
matrix(v,byrow=TRUE,nrow=2)


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

Wir haben jetzt also eine 2 mal 3 Matrix. Dies konnten wir durch das `nrow` Argument erzeugen. Wie legen wir nun die Reihenfolge der Elemente fest? Wir könnten zuerst die Spalten füllen (wie es im Beispiel gerade eben passiert ist) oder zuerst die Zeilen. Das `byrow` Argument ermögliocht es uns, dies festzulegen. Hier zwei Beispiele:

In [7]:
matrix(1:16,byrow = FALSE,nrow=4)

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [8]:
matrix(1:16, byrow=TRUE, nrow=4)

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

## Matrizen aus Vektoren erstellen

Wir können mehrere Vektoren kombinieren, um sie in eine Matrix einzuspielen. Stell dir beispielhaft die beiden folgenden Vektoren von Aktienpreisen vor:

In [9]:
# Historische Aktien Schluss-Preise KW 49 / 2019 
# Google
GOOG <- c(1289.92,1295.28,1320.54,1328.13,1340.61) 
GOOG

# Tesla
TSLA <- c(334.86,336.20,33.02,330.36,335.89) 
TSLA

[1] 1289.92 1295.28 1320.54 1328.13 1340.61

[1] 334.86 336.20  33.02 330.36 335.89

In [10]:
aktien <- c(GOOG,TSLA)
aktien

[1] 1289.92 1295.28 1320.54 1328.13 1340.61  334.86  336.20   33.02  330.36
[10]  335.89

In [19]:
aktien.matrix <- matrix(aktien,byrow=TRUE,nrow=2)

In [20]:
aktien.matrix

[,1]    [,2]    [,3]    [,4]    [,5]   
[1,] 1289.92 1295.28 1320.54 1328.13 1340.61
[2,]  334.86  336.20   33.02  330.36  335.89

In [16]:
tage <- c('Mo','Di','Mi','Do','Fr')
aktien.namen <- c('GOOG','TSLA')

In [21]:
# colnames(aktien.matrix) <- tage
# rownames(aktien.matrix) <- aktien.namen

colnames(aktien.matrix) <- c('Mo','Di','Mi','Do','Fr')
rownames(aktien.matrix) <- c('GOOG','TSLA')

## Matrizen benennen

Jetzt wo wir unsere Matrix erstelt haben ist es naheliegend die Zeilen und Spalten für einen besseren Zugriff zu benennen. Das funktioniert prinzipiell gleich wie die `names()` Funktion für Vektoren: Wir definieren `colnames()` (für die Spalten) und `rownames()` (für die Zeilen). Bennenen wir nun unsere Aktien-Matrix:

In [22]:
aktien.matrix

Mo      Di      Mi      Do      Fr     
GOOG 1289.92 1295.28 1320.54 1328.13 1340.61
TSLA  334.86  336.20   33.02  330.36  335.89

Sieht gut aus! Wir bauen uns so langsam etwas wirklich funktionelles auf. So langsam erinnert uns das an eine Tabelle.

Das waren die Grundlagen zur Erstellung von Matrizen. In der nächsten Lektion werden wir eine Matrix von Aktienkursen erstellen, behaltet den Code also für spätere Verweise.

Herzlichen Glückwunsch! Sie sind mit Lektion 11 fertig!