# Tag 1. Kapitel 4. Listen (Lists)

## Lektion 22. R Listen Grundlagen

Wir kennen nun Vektoren, Matrizen und Data Frames. Als letztes im Kapitel der R Grundlagen können wir uns nun die eingebaute Daten Struktur "Liste" anschauen.

Listen erlauben es uns eine Vielzahl an Daten Strukturen innerhalb einer einzigen Variable zu speichern. Das heißt, einen Vektor, eine Matrix und/oder einen Data Frame; alles innerhalb einer einzigen Liste.

In [1]:
# Vektor erstellen
v <- c(1,2,3,4,5)

# Matrix erstellen
m <- matrix(1:10,nrow=2)

# Data Frame erstellen
df <- women

In [2]:
v

[1] 1 2 3 4 5

In [3]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [4]:
df

height weight
1  58     115   
2  59     117   
3  60     120   
4  61     123   
5  62     126   
6  63     129   
7  64     132   
8  65     135   
9  66     139   
10 67     142   
11 68     146   
12 69     150   
13 70     154   
14 71     159   
15 72     164

## Die Nutzung von list()

Wir können nun die `list()` Funktion verwenden, um alle Datenstrukturen zu kombinieren:

In [5]:
li <- list(v,m,df)

In [6]:
li

[[1]]
[1] 1 2 3 4 5

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

Dabei fällt auf, dass `list()` allen Objekten in der Liste eine Nummer zugeordnet hat. Diese Nummern können wir wie folgt durch Namen ersetzen:

In [7]:
li <- list(beispiel_vek = v,beispiel_mat = m, beispiel_df = df)

In [8]:
li

$beispiel_vek
[1] 1 2 3 4 5

$beispiel_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$beispiel_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

### Objekte aus Listen auswählen

Wir können die Klammern-Notation nutzen, um Objekte aus einer Liste anzuzeigen. Und doppelte Klammern, um den tatsächlichen Inhalt des Objektes zu erhalten. Schauen wir uns das beispielhaft an:

In [9]:
# Einfache Klammern
li[1] # Nach Index
class(li[1])

$beispiel_vek
[1] 1 2 3 4 5

[1] "list"

In [11]:
# Nach Namen
li['beispiel_vek']

$beispiel_vek
[1] 1 2 3 4 5

In [12]:
# Beachtete den Typ
class(li['beispiel_vek'])

[1] "list"

In [14]:
# Doppelte Klammern um den tatsächlichen Inhalt eines Objektes zu erhalten
li[['beispiel_vek']]
class(li[['beispiel_vek']])

[1] 1 2 3 4 5

[1] "numeric"

In [16]:
# Wir können auch die $ Notation verwenden
li$beispiel_vek
class(li$beispiel_vek)

[1] 1 2 3 4 5

[1] "numeric"

Zusätzlich können wir indexieren, sobald wir ein Objekt aus der Liste ausgewählt haben.

In [18]:
li[['beispiel_vek']][3]

[1] 3

In [22]:
li[['beispiel_mat']]
m2 <- li[['beispiel_mat']]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [23]:
li[['beispiel_mat']][1,]
m2[1,]

[1] 1 3 5 7 9

[1] 1 3 5 7 9

In [24]:
li[['beispiel_mat']][1:2,1:2]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [26]:
li[['beispiel_df']]['height']
class(li[['beispiel_df']])

height
1  58    
2  59    
3  60    
4  61    
5  62    
6  63    
7  64    
8  65    
9  66    
10 67    
11 68    
12 69    
13 70    
14 71    
15 72

[1] "data.frame"

# Listen kombinieren

Listen können außerdem auch andere Listen beinhalten. Wir können Listen durch die bereits bekannte Funktion `c()` kombinieren:

In [27]:
doppelte_liste <- c(li,li)

In [28]:
doppelte_liste

$beispiel_vek
[1] 1 2 3 4 5

$beispiel_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$beispiel_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

$beispiel_vek
[1] 1 2 3 4 5

$beispiel_mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$beispiel_df
   height weight
1      58    115
2      59    117
3      60    120
4      61    123
5      62    126
6      63    129
7      64    132
8      65    135
9      66    139
10     67    142
11     68    146
12     69    150
13     70    154
14     71    159
15     72    164

In [29]:
str(doppelte_liste)

List of 6
 $ beispiel_vek: num [1:5] 1 2 3 4 5
 $ beispiel_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ beispiel_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...
 $ beispiel_vek: num [1:5] 1 2 3 4 5
 $ beispiel_mat: int [1:2, 1:5] 1 2 3 4 5 6 7 8 9 10
 $ beispiel_df :'data.frame':	15 obs. of  2 variables:
  ..$ height: num [1:15] 58 59 60 61 62 63 64 65 66 67 ...
  ..$ weight: num [1:15] 115 117 120 123 126 129 132 135 139 142 ...


Herzlichen Glückwunsch! Sie sind mit Lektion 22 fertig!